"use client";
import { useEffect, useMemo, useState } from "react";
import { HeartIcon, InformationCircleIcon, PlayIcon, XMarkIcon } from "@heroicons/react/24/outline";
import { classifier } from "@/lib/classifier";
import { posts } from "@/data/posts";
const demoIds=["ski","grandpa","gpa","ambiguous"];
export function Feed(){
 const [dev,setDev]=useState(false),[selected,setSelected]=useState<string[]>([]),[demo,setDemo]=useState(false),[step,setStep]=useState(0),[overrides,setOverrides]=useState<Record<string,boolean>>({});
 useEffect(()=>{if(demo) document.getElementById(demoIds[step])?.scrollIntoView({behavior:"smooth",block:"center"})},[demo,step]);
 const featured=useMemo(()=>posts.map(p=>({...p,result:classifier.classify(p.caption)})),[]);
 return <><section className="mx-auto max-w-6xl px-5 pb-12 pt-10"><div className="mx-auto max-w-2xl text-center"><div className="mb-4 text-xs font-bold uppercase tracking-[.18em] text-[var(--accent)]">An independent feature concept for Instagram</div><h1 className="font-serif text-5xl leading-[.98] tracking-[-.055em] sm:text-7xl">Sometimes <em className="text-[var(--accent)]">Like</em> is the wrong word.</h1><p className="mx-auto mt-5 max-w-xl text-lg leading-8 text-[var(--muted)]">When context is unmistakably memorial, the interaction adapts. When it is not, nothing changes.</p><div className="mt-7 flex justify-center gap-3"><button onClick={()=>{setDemo(true);setStep(0)}} className="flex items-center gap-2 rounded-full bg-[var(--ink)] px-5 py-3 text-sm font-bold text-white"><PlayIcon className="h-4 w-4"/>Run 30-second demo</button><button onClick={()=>setDev(!dev)} className="rounded-full border border-[var(--line)] bg-white px-5 py-3 text-sm font-bold">{dev?"User view":"Developer view"}</button></div></div></section>
 {demo&&<div className="sticky top-16 z-20 border-y border-[#dfc8cf] bg-[#f8edf0] px-5 py-3"><div className="mx-auto flex max-w-3xl items-center gap-4 text-sm"><b>Demo {step+1}/4</b><span className="text-[var(--muted)]">{["Normal post stays Like","Sincere memorial becomes Commemorate","Figurative RIP stays Like","Uncertain wording asks the author"][step]}</span><button disabled={step===3} onClick={()=>setStep(s=>Math.min(3,s+1))} className="ml-auto rounded-full bg-[var(--accent)] px-4 py-2 font-bold text-white disabled:opacity-40">Next</button><button aria-label="Close demo" onClick={()=>setDemo(false)}><XMarkIcon className="h-5 w-5"/></button></div></div>}
 <div className="mx-auto max-w-[520px] space-y-8 px-4 pb-24">{featured.map((post)=>{const isDemo=demo&&demoIds[step]===post.id; const commemorate=post.result.interaction==="commemorate"||overrides[post.id]; const pressed=selected.includes(post.id); return <article id={post.id} key={post.id} className={`scroll-mt-36 overflow-hidden rounded-[28px] border bg-white shadow-[0_18px_60px_rgba(45,38,32,.07)] transition ${isDemo?"border-[var(--accent)] ring-4 ring-[#7d29421b]":"border-[var(--line)]"}`}><div className="flex items-center gap-3 p-4"><div className="grid h-10 w-10 place-items-center rounded-full bg-[#eee9e4] text-xs font-bold">{post.name.slice(0,1)}</div><div><b className="text-sm">{post.user}</b><div className="text-xs text-[var(--muted)]">{post.location}</div></div></div><img src={post.image} alt="" className="aspect-[4/3] w-full object-cover"/><div className="p-5"><button onClick={()=>setSelected(v=>pressed?v.filter(x=>x!==post.id):[...v,post.id])} className={`flex w-full items-center gap-3 rounded-2xl border px-4 py-3.5 text-left font-bold transition active:scale-[.99] ${commemorate?"border-[#dfc1ca] bg-[var(--accent-soft)] text-[var(--accent)]":"border-[var(--line)] hover:bg-[#f8f6f3]"}`}><HeartIcon className={`h-6 w-6 ${pressed?"fill-current":""}`}/>{commemorate?(pressed?"Commemorated":"Commemorate"):(pressed?"Liked":"Like")}<span className="ml-auto text-xs font-medium opacity-55">{commemorate?"Honor their memory":"Show appreciation"}</span></button><p className="mt-4 text-[15px] leading-6"><b className="mr-2">{post.user}</b>{post.caption}</p>
 {post.result.interaction==="confirm"&&!overrides[post.id]&&<div className="mt-4 rounded-2xl border border-[#eadce1] bg-[#fcf5f7] p-4"><div className="flex gap-2 text-sm font-bold"><InformationCircleIcon className="h-5 w-5 text-[var(--accent)]"/>Author preview</div><p className="mt-2 text-sm leading-5 text-[var(--muted)]">This post may be commemorating someone. Would you like people to see “Commemorate” instead of “Like”?</p><div className="mt-3 flex gap-2"><button onClick={()=>setOverrides(v=>({...v,[post.id]:true}))} className="rounded-full bg-[var(--accent)] px-3 py-2 text-xs font-bold text-white">Use Commemorate</button><button className="rounded-full border border-[var(--line)] bg-white px-3 py-2 text-xs font-bold">Keep Like</button></div></div>}
 {dev&&<div className="mt-4 rounded-2xl bg-[#f5f3f0] p-4 text-xs"><div className="flex justify-between"><b>{post.result.label.toUpperCase()}</b><b>{post.result.confidence.toFixed(1)}%</b></div><div className="my-2 text-[var(--muted)]">Interaction: {post.result.interaction.toUpperCase()}</div><ul className="space-y-1">{post.result.signals.map(s=><li key={s}>• {s}</li>)}</ul></div>}</div></article>})}</div></>;
}
